sudo: required
dist: trusty
cache:
  directories:
    - node_modules
language: node_js
env:
  global:
    - CXX=g++-4.8
    - DISPLAY=:99.0
    - CHROME_BIN=/usr/bin/google-chrome
# setting up Chrome for e2e tests
apt:
  sources:
    - google-chrome
  packages:
    - dpkg  # see https://github.com/travis-ci/travis-ci/issues/9361
    - google-chrome-stable

# Building for a specific set of node versions
node_js:
          - '8'

before_install:
  - sudo apt-get --allow-unauthenticated install -y dpkg
  - sudo apt-get --only-upgrade --allow-unauthenticated install google-chrome-stable
  - google-chrome --version
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

# the following step should start the virtual X frame buffer: Xvfb process         
before_script:
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 #wait a while before xvfb to start
after_script:
#  - "sh -e /etc/init.d/xvfb stop"
